### ISSUE TITLE
request update to EAPI=6 where possible.

### ISSUE THREAD

**Issue by 2011** [jorgicio/jorgicio-gentoo-overlay#154]
Don't know everything involved in doing this, but it is especially helpful to apply user patches (in this case, I am thinking of games-emulation/sdlmame, where I add hacks that I have ROMs for).

**Comment by jorgicio** [comment]
Hi! I'll try to check this and rebump those packages. This may take some time. Sorry for the inconveniences.

**Comment by jorgicio** [comment]
Update ended, so I close this.
