### ISSUE TITLE
Seperate plasma deps from kvantum themes

### ISSUE THREAD

**Issue by marcthe12** [jorgicio/jorgicio-gentoo-overlay#178]
Materia-kde  pulls the whole plasma desktop.

As materia-kde provides a kvnatumn theme which could be used to just theme qt outside the plasma DE, have a use flag that disable plasma.

**Comment by jorgicio** [comment]
Done. Since arc-kde is made for KDE, the `plasma` USE-flag is enabled by default, but you can disable it if you want.
