### ISSUE TITLE
www-plugins/opera-ffmpeg-codecs-76.0.3809.132: does not compile

### ISSUE THREAD

**Issue by tsjk** [jorgicio/jorgicio-gentoo-overlay#182]
Unfortunately some attention is needed to make things work sometimes. In this particular case it's not much.
Instead of just dropping the patches for 73, this also needs to be amended with patches for 76. Copying them from chromium in portage seems to make this compile at least.
Feel free to view https://github.com/tsjk/gentoo-ebuilds/tree/master/www-plugins/opera-ffmpeg-codecs for guidance. I just copied what you have here and added the patches.
Thank you for this repo!

**Comment by jorgicio** [comment]
Hi! I just checked your ebuild and you're right, I forgot the patches for chromium. I hope this may help to build the codecs for Opera.

Thanks for your contribution!
