### ISSUE TITLE
app-emulation/packettracer-7.2.1 emerge error

### ISSUE THREAD

**Issue by benhard123** [jorgicio/jorgicio-gentoo-overlay#183]
every time i installing packettracer alway get error like this:

>>> Install app-emulation/packettracer-7.2.1 into /var/tmp/portage/app-emulation/packettracer-7.2.1/image
chmod: cannot access '/var/tmp/portage/app-emulation/packettracer-7.2.1/image/opt/packettracer/extensions/NetacadExamPlayer/ptplayer/*.*': No such file or directory
 * ERROR: app-emulation/packettracer-7.2.1::jorgicio failed (install phase):
 *   fperms failed

[build.log](https://github.com/jorgicio/jorgicio-gentoo-overlay/files/3641768/build.log)

**Comment by benhard123** [comment]
Ok, I made the fix, i just changing the *.* from the ebuild to exact name in the directory
[packettracer-7.2.1.zip](https://github.com/jorgicio/jorgicio-gentoo-overlay/files/3667444/packettracer-7.2.1.zip)

**Comment by jorgicio** [comment]
Hi! Sorry for being late. Thanks for the fix.

Also, you may consider sending a PR next time you fix something :)
