### ISSUE TITLE
properties-cpp dev-cpp VS dev-libs

### ISSUE THREAD

**Issue by okias** [jorgicio/jorgicio-gentoo-overlay#185]
Hey, while I'm trying to install anbox, I noticed there is multiple versions of properties-cpp and also they are put under different categories [1] [2].

I noticed your ebuild look most updated, so I wonder if we could maybe push it into mainline gx86 and make it unified.

Any ideas, why choose dev-cpp or dev-libs ?

Thank you

[1] http://gpo.zugaina.org/dev-libs/properties-cpp
[2] http://gpo.zugaina.org/dev-cpp/properties-cpp

**Comment by jorgicio** [comment]
Both are actually the same, but I don't know why a C++ library is in a dev-libs category and not dev-cpp. Anyways, I'll fix it then.

Thanks.
