### ISSUE TITLE
app-editors/vscode-bin should depend on app-accessibility/at-spi2-atk?

### ISSUE THREAD

**Issue by asaparov** [jorgicio/jorgicio-gentoo-overlay#200]
Without `app-accessibility/at-spi2-atk` installed, running vscode causes the following error on my machine:
```
/opt/vscode/bin/../code: error while loading shared libraries: libatk-bridge-2.0.so.0: cannot open shared object file: No such file or directory
```

After installing that package, vscode works fine.

**Comment by jorgicio** [comment]
It should, but I didn't have any problem with that, but I realized it was previously installed in my distro.

I'll add it as a dependency.
