### ISSUE TITLE
app-text/bookworm /usr/bin/Exe-Name  wish

### ISSUE THREAD

**Issue by Ulenrich** [jorgicio/jorgicio-gentoo-overlay#202]
The bookworm ebuild creates
/usr/bin/com.github.babluboy.bookworm
as an executable name. I couldn't find the newly emerged app using 
# ls /usr/bin/bookworm*
therefore. I don't like this java style naming.

Could the executable just named /usr/bin/bookworm
instead ? (I know I can create a symlink though)

**Comment by jorgicio** [comment]
As shown in the https://github.com/babluboy/bookworm repository, that's the binary's name as always has been. Don't ask me why, but I agree with you with that weird naming.

**Comment by Ulenrich** [comment]
Arrrgh, yeah: The name symbolizes the worm:
com.github.babluboy.bookworm
