### ISSUE TITLE
media-video/olive-1.2: does it really need video acceleration?

### ISSUE THREAD

**Issue by nick87720z** [jorgicio/jorgicio-gentoo-overlay#205]
Both issue and question. I see olive-1.2 ebuild requires ffmpeg with both vaapu and vdpau. I have intel, thus only vaapi. However, it compiled and started without errors, when I did it with --nodeps (it only required to rebuild ffmpeg with +vdpau.

As for any support for VA - I searched right in github repo for vdpau and vaapi (no result). For "video acceleration" I found only one wiki page:
https://github.com/olive-editor/olive/wiki/Frei0r-Support-EOL

**Comment by jorgicio** [comment]
Hi! video acceleration may not be needed, so I'll leave it as optional adding new USE-flags.

Also, keep in mind that Olive editor is currently in development (at least recent versions) and now I noted that frei0r support may be deprecated soon.

Anyways, I'll fix it then. Thank you.
