### ISSUE TITLE
Atom-bin 1.44.0

### ISSUE THREAD

**Issue by Makersmarx** [jorgicio/jorgicio-gentoo-overlay#208]
First, thanks I have utilized your overlay for some time and appreciate you sharing them. Second, with the recent version bump on Atom I am being asked to pull systemd. In my make.conf I have strictly put -systemd, but its being required now with Atom. I tested the same version from another overlay and it does not require the changes and installs without request of pulling systemd.  Thanks for your review

The following USE changes are necessary to proceed:
 (see "package.use" in the portage(5) man page for more details)
required by sys-apps/systemd-245_rc1-r1::gentoo
required by app-editors/atom-bin-1.44.0::jorgicio
required by @selected
required by @world (argument)
>=sys-apps/dbus-1.12.16 systemd

**Comment by MarcoKull** [comment]
I would also greatly appreciate removing the systemd dependency.

**Comment by simonvanderveldt** [comment]
+1 :)

@jorgicio Is there a direct dependency on a library from systemd or something like that?

**Comment by jorgicio** [comment]
Hi! Sorry for the inconveniences.

First of all, I didn't bumped that version, it was did it by someone else who sent a PR. After this issue, I noted that, so I fixed it removing systemd as dependency.

Resync and try again.

Thank you!

**Comment by simonvanderveldt** [comment]
@jorgicio Could you could drop the lz4 and wayland dependencies as well or put them behind USE flags?
Been using Atom daily and they don't seem to be required, also checked and I don't see them in [Arch's PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/atom) either.

**Comment by jorgicio** [comment]
@simonvanderveldt Done. Thanks!
