### ISSUE TITLE
Packet Tracer has old libpng requirement.

### ISSUE THREAD

**Issue by knownothingbozo** [jorgicio/jorgicio-gentoo-overlay#214]
emerge: there are no ebuilds to satisfy "media-libs/libpng:1.2".
(dependency required by "app-emulation/packettracer-7.2.1::jorgicio" [ebuild])
(dependency required by "packettracer" [argument])

I tried installing libpng-compat 1.2.59. I tried installing the older version of libpng from source off the official site. I also tried taking the ebuild and modifying the slot requirement. I know i'm probably just stupid and that's not how it works, but I tired everything I could think of.

**Comment by jorgicio** [comment]
Sorry, older versions of libpng are turned into libpng-compat, so I'll fix it then.

**Comment by knownothingbozo** [comment]
Thank you very much. I really appreciate the promptness. You're awesome!
