### ISSUE TITLE
Yakyak-bin-1.5.4.ebuild: Manifest not found

### ISSUE THREAD

**Issue by shnups** [jorgicio/jorgicio-gentoo-overlay#216]
Hello,

First of all, thanks for providing this great overlay and packaging all these programs.

Just have a quick problem when upgrading @world on my machine regarding yakyak-bin:
```Manifest not found for '/var/lib/layman/jorgicio/net-im/yakyak-bin/yakyak-bin-1.5.4.ebuild```

Indeed, the manifest file (as well as the metadata.xml file) were removed in commit [56480aae940010a4e3d383120d43d5adfa96a98a](https://github.com/jorgicio/jorgicio-gentoo-overlay/commit/56480aae940010a4e3d383120d43d5adfa96a98a#diff-9e826f44ca1b2ede392bff03b97b2208) 2 days ago.

Thanks in advance.

**Comment by jorgicio** [comment]
Hi.
Two days ago, I did some cleanup of packages I won't maintain (mostly deprecated or with failures). Maybe I got rid of the Manifest file.
It'll be ready then, so please, wait a minute.

Thanks for the report!

Anyways, I'll restore the Manifest in

**Comment by shnups** [comment]
Totally forgot about this.
Anyhow, thanks for the quick update and maintaining this ebuild!
