### ISSUE TITLE
dev-qt/qtstyleplugins-5.0.0_p20170311: Error while installing kde-frameworks/kwidgetsaddons-5.67.0

### ISSUE THREAD

**Issue by tastytea** [jorgicio/jorgicio-gentoo-overlay#218]
```
CMake Error at /usr/lib64/cmake/Qt5Widgets/Qt5Widgets_QBB10StylePlugin.cmake:4 (_populate_Widgets_plugin_properties):                                                                                       
  _populate_Widgets_plugin_properties Macro invoked with incorrect arguments                          
  for macro named: _populate_Widgets_plugin_properties                                                
Call Stack (most recent call first):                                                                  
  /usr/lib64/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:213 (include)          
  /usr/lib64/cmake/Qt5/Qt5Config.cmake:28 (find_package)                                              
  CMakeLists.txt:18 (find_package)
```

`/usr/lib64/cmake/Qt5Widgets/Qt5Widgets_QBB10StylePlugin.cmake` is from dev-qt/qtstyleplugins-5.0.0_p20170311. After uninstalling it, the upgrade went through.

There is a [similar issue](https://bugs.gentoo.org/703306#c5) on bugs.gentoo.org, the comments suggest that it is likely that a CMake macro changed its arguments in a backwards incompatible way.

**Comment by jorgicio** [comment]
AFAIK, by reading the link you sent, I noted the issue may happen when using Qt 5.14. I'm on Calculate Linux with amd64 and using Qt 5.13, and the package built fine (but not using it because I'm using KDE Plasma and it doesn't need it).

**Comment by jorgicio** [comment]
Hi again.
Just tried to build again now that both cmake and qt are upgraded (cmake: 3.16.5, qt: 5.14.1) and working.

**Comment by tastytea** [comment]
After uninstalling `dev-qt/qtstyleplugins` upgrading the qt packages, and installing `dev-qt/qtstyleplugins` again, `kde-frameworks/kwidgetsaddons` builds fine here too.
