### ISSUE TITLE
Unnecessary dependencis in zoom-3.5.374815.0324.ebuild

### ISSUE THREAD

**Issue by Barnoid-** [jorgicio/jorgicio-gentoo-overlay#220]
net-im/zoom-3.5.374815.0324.ebuild contains superfluous library dependencies, in particular, the newly introduced media-libs/libglvnd which causes a lot of headache for people with Nvidia cards (see https://forums.gentoo.org/viewtopic-t-1109388-start-25-postdays-0-postorder-asc-highlight-.html). The dependency can be safely removed (tested on an amd64 machine without libglvnd installed).

Furthermore, the zoom binary bundles all Qt libraries; it should be possible to use those instead of depending on the system Qt. Running with LD_LIBRARY_PATH=. ./zoom loads all Qt libraries from the local (install) directory.

**Comment by lourdas** [comment]
Agree. The huge pain is the qtwebengine. Until now, I managed to cope without it, but now the official zoom ebuild (and yours) require is as a RDEPEND. Since it's already bundled, can't the binary use those instead of ours in the system?

**Comment by lkraav** [comment]
Another :heavy_plus_sign: 1 here. Literally only Zoom seems to depend on qtwebengine

```
leho@gusto profiles $ equery d qtwebengine
 * These packages depend on qtwebengine:
net-im/zoom-3.5.372466.0322-r1 (dev-qt/qtwebengine:5)
```

**Comment by lourdas** [comment]
I hacked version zoom-3.5.372466.0322.ebuild from commit 089c5b9b21faac03d977e781ca1486bba9305356 and copied it to my local overlay as a new version (zoom-3.5.374815.0324-r1.ebuild), ebuild manifest and everything works as previously. The camera works, all is good.

I suggest you do the same.

**Comment by jorgicio** [comment]
Hi. Sorry for being late.
To be honest with you, I just copied the official ebuild taken from the Official Portage Tree and bumped to the most recent version, and I didn't check this comes with this issue. I'll check it and have an answer soon.

Thank you.
