### ISSUE TITLE
Problem with official gentoo zoom ebuild

### ISSUE THREAD

**Issue by Fulgurance** [jorgicio/jorgicio-gentoo-overlay#221]
Hello, i first thanks you for your work jorgicio. You provided some ebuild during long time !

I contact you because recently gentoo have added zoom officially in his repository. I have switched into official zoom ebuild. But there are 2 problems: bad desktop icon, and camera don't work. I would like to see your zoom ebuild, but it was deleted .

Can you look my 2 bugs report to help the gentoo maintainer please ?
 
https://bugs.gentoo.org/715088
https://bugs.gentoo.org/715106

**Comment by lourdas** [comment]
Look at https://github.com/jorgicio/jorgicio-gentoo-overlay/issues/220#issuecomment-605432291

**Comment by jorgicio** [comment]
Hello, I just watched this. As I saw in the links you sent, it looks like the issue is fixed, so I'll remove my ebuild because it won't necessary anymore.

Thank you.
