### ISSUE TITLE
x11-misc/optimus-manager 

### ISSUE THREAD

**Issue by zarMarco** [jorgicio/jorgicio-gentoo-overlay#223]
Hi, can I use it with openrc? I added your overlay and I installed optimus-manager and optimus-manager-qt.
I added optimus-manager with rc-update but when I try to started from /etc/init.d I had an error with optimus-manager-daemon

**Comment by jorgicio** [comment]
Hi.
As mentions in the post installation message: Optimus Manager can be used only of other Optimus-related daemons (like Bumblebee) are shutdown and disabled. Optimus Manager and Bumblebee can't get along together.

**Comment by zarMarco** [comment]
Oh yes, I've disabled bumblebee, but I don't know if I can use this with openrc. So after lunch I will retry

**Comment by jorgicio** [comment]
As I see no answers, I may close this issue, but you feel free to re-open it if any issue.

**Comment by zarMarco** [comment]
Sorry man if I no answer in the last days but I had some problems. One little question, are you sure that this package goes with openrc? I have disable bumblebee and bbswitch
