### ISSUE TITLE
media-gfx/openboard-1.5.4: Dependency missing: media-libs/libass

### ISSUE THREAD

**Issue by jan42** [jorgicio/jorgicio-gentoo-overlay#226]
Hey, thanks for the fix for issue 225!
I got it to compile (and run) after I emerged media-libs/libass-0.14.0 (stable).
My prior attempt got an "ld: cannot find -lass" error.

**Comment by jorgicio** [comment]
My bad, it didn't fail here because I already had installed that package. I'll fix it now.

Thanks!
