### ISSUE TITLE
media-gfx/openboard-1.5.4: Dependency missing: x11-libs/libva

### ISSUE THREAD

**Issue by 0x0badc0de** [jorgicio/jorgicio-gentoo-overlay#227]
Build fails with
```
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lva-x11
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lva
```

**Comment by jorgicio** [comment]
Do you have installed x11-libs/libva ? If not, may be this is a missing dependency I should add.

**Comment by 0x0badc0de** [comment]
Yes, I've installed libva and was able to build the package. Thanks!

**Comment by jorgicio** [comment]
Great! This means x11-libs/libva needs to be added as a dependency. Thanks for the report.
