### ISSUE TITLE
Problem with eix-sync

### ISSUE THREAD

**Issue by y0rune** [jorgicio/jorgicio-gentoo-overlay#228]
[10] "jorgicio" /usr/repos/jorgicio (cache: parse|ebuild*#metadata-md5#metadata-flat#assign)
     Reading category 167|174 ( 95): x11-misc... * This DEAD eclass must not be inherited directly by an ebuild.
 * ERROR: x11-misc/optimus-manager-qt-9999::jorgicio failed (depend phase):
 *   Removal due on 2020-04-16.
 *
 * Call stack:
 *                        ebuild.sh, line 609:  Called source '/usr/repos/jorgicio/x11-misc/optimus-manager-qt/optimus-manager-qt-9999.ebuild'
 *   optimus-manager-qt-9999.ebuild, line   6:  Called inherit 'git-r3' 'kde5-functions' 'qmake-utils' 'xdg-utils'
 *                        ebuild.sh, line 314:  Called __qa_source '/usr/portage/eclass/kde5-functions.eclass'
 *                        ebuild.sh, line 112:  Called source '/usr/portage/eclass/kde5-functions.eclass'
 *            kde5-functions.eclass, line  21:  Called die
 * The specific snippet of code:
 *      die "Removal due on 2020-04-16."
 *
 * If you need support, post the output of `emerge --info '=x11-misc/optimus-manager-qt-9999::jorgicio'`,
 * the complete build log and the output of `emerge -pqv '=x11-misc/optimus-manager-qt-9999::jorgicio'`.
 * Working directory: '/usr/lib64/python3.6/site-packages'
 * S: '/optimus-manager-qt-9999'

**Comment by jorgicio** [comment]
This issue was fixed some days ago. See #219 for more details.
I think you may resync the overlay first.
