### ISSUE TITLE
media-gfx/openboard-1.5.4: Dependency missing: media-libs/opus

### ISSUE THREAD

**Issue by 0x0badc0de** [jorgicio/jorgicio-gentoo-overlay#242]
`opus` was installed on my system as a dependency of some another package and now it's removed.
Since then emerge fails with
```
/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: cannot find -lopus
collect2: error: ld returned 1 exit status
```
Emerged `opus` back and `openboard` can be built.

**Comment by jorgicio** [comment]
Opus added. Thanks for reporting!
