### ISSUE TITLE
net-im/cawbird-1.1.0 eapply_user (or default) must be called in src_prepare()

### ISSUE THREAD

**Issue by Dr-Terrible** [jorgicio/jorgicio-gentoo-overlay#243]
ebuild `net-im/cawbird-1.1.0::jorgicio` is missing a `src_prepare` section:

```ebuild
src_prepare() {
    default
}
```

**Comment by jorgicio** [comment]
That's weird because the inherits should add that functions without calling it. Anyways, I'll add it then.
