### ISSUE TITLE
games-emulation/reicast build failure | libswirl/sdl/sdl.cpp:252: undefined reference

### ISSUE THREAD

**Issue by jeandestouches** [jorgicio/jorgicio-gentoo-overlay#244]
Hi,
I'm unable to compile reicast on my system. I tried version 20.04, and master (9999), same error : 

```
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: obj-dreamcast-x64-sse4_1/sdl/sdl.build_obj: in function `sdl_window_create(void**, void**)':
/var/tmp/portage/games-emulation/reicast-20.04/work/reicast-emulator-r20.04/reicast/linux/../../libswirl/sdl/sdl.cpp:251: undefined reference to `sdlgl_CreateWindow(bool, int, int, int, void**, void**)'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /var/tmp/portage/games-emulation/reicast-20.04/work/reicast-emulator-r20.04/reicast/linux/../../libswirl/sdl/sdl.cpp:252: undefined reference to `sdlgl_CreateWindow(bool, int, int, int, void**, void**)'
collect2: error: ld returned 1 exit status
make: *** [Makefile:266: reicast.elf] Error 1
```
Any help ? Thanks

**Comment by jorgicio** [comment]
Have you tried to build with the USE=sdl enabled? It's masked because SDL support is broken.

**Comment by jorgicio** [comment]
I built this package with SDL disabled and works fine here. May be this issue is related with that.

**Comment by jeandestouches** [comment]
Thanks for the suggestion jorgicio, it worked with USE="-sdl"
I thought the sdl issue was fixed (from what I read on reicast github), I guess it is not. I will report the issue there instead.

**Comment by jorgicio** [comment]
I thought the same so, also, when you emerge this package, the sdl USE-flag should be not be enabled (I masked it from the profile) unless you have enabled it manually doing an unmask (which is kinda tricky).

I hope this may help you.
