### ISSUE TITLE
x11-misc/emojione-picker fails to start: ImportError: No module named gi

### ISSUE THREAD

**Issue by redblade7** [jorgicio/jorgicio-gentoo-overlay#258]
x11-misc/emojione-picker fails to start with the error:

```
Traceback (most recent call last):
  File "/usr/bin/emojione-picker", line 20, in <module>
    from gi import require_version
ImportError: No module named gi
```

Is a dependency missing?

**Comment by redblade7** [comment]
If this helps, I was required to remove the `python_targets_python2_7` USE flag before install, and I see the program does not support Python 3. Perhaps the program is being partially installed?

**Comment by jorgicio** [comment]
> If this helps, I was required to remove the `python_targets_python2_7` USE flag before install, and I see the program does not support Python 3. Perhaps the program is being partially installed?

Yes, maybe, I don't have this issue here, but I hope the change I did helps.

**Comment by redblade7** [comment]
Still getting the same error. I am using `python_targets_python3_7`
