### ISSUE TITLE
caffeine-ng new version available

### ISSUE THREAD

**Issue by PF4Public** [jorgicio/jorgicio-gentoo-overlay#278]
There is new version upstream: https://github.com/caffeine-ng/caffeine-ng/releases
Please update

**Comment by PF4Public** [comment]
Nwm, copied into my overlay.

**Comment by jorgicio** [comment]
Hi. Sorry, I though you read the message I left in the main description: I'm not maintaining this overlay in the meantime. More details in the README.

Sorry for the inconveniences.

**Comment by PF4Public** [comment]
> Hi. Sorry

You shouldn't be apologizing: I should. 

Indeed I had read the README, but only after submitting this issue, thus taken the ebuild and updated in my overlay. No problem!
