### ISSUE TITLE
games-emulation/melonds links to non existant library

### ISSUE THREAD

**Issue by dakrk** [jorgicio/jorgicio-gentoo-overlay#306]
[This commit](https://github.com/Arisotura/melonDS/commit/e3b4350f44a51d0012457a556dc04dfd0ba267d4) in melonDS included a library for the DSi's DSP in the source tree, however, this ebuild is somehow making cmake link to it dynamically but the library doesn't get installed, so executing melonDS results in it returning an error because it cannot find it (libteakra.so)

**Comment by jorgicio** [comment]
Ok, can you send a PR, please? Thank you.

**Comment by dakrk** [comment]
Fixed with #307
